STATE_OFFICES_MAP = {
    "AL": [
        "Alabama",
    ],
    "AZ": [
        "AZ - Legacy Home Group",
        "AZ - Team Minik",
        "AZ - The Ramos Legacy Group",
        "AZ The X Team",
        "AZ Valley Wide Agents",
        "Arizona",
    ],
    "CA": [
        "CA -  Alvarez  Associates",
        "CA - AqTEAM",
        "CA - Cal Home CO",
        "CA - Claudia Fernandez Team",
        "CA - Excelsis",
        "CA - Natividad Realty Group",
        "CA - Team California",
        "CA - Team Turlock",
        "CA - The Dominguez Group",
        "CA - The Dream Team",
        "CA - The Esparza Group",
        "CA - Trujillo Empire Team",
        "CA David Fletes Team",
        "CA Exclusive Team",
        "CA LFRO",
        "CA Living in N California",
        "CA M Group",
        "CA MJG  Associates",
        "CA Singer Realty Group",
        "CA TC Claudia Lopez",
        "CA Team Innovative",
        "CA The Cedeno Team",
        "CA The Luevanos Group",
        "California",
    ],
    "DC": [
        "District of Columbia",
    ],
    "FL": [
        "FL - The Dominguez Group",
        "FL - Three Two One",
        "FL Global Homes Group",
        "FL Platinum Home Group",
        "FL The Collective Florida",
        "FL The Friendly Homes Group",
        "Florida",
    ],
    "GA": [
        "Georgia",
    ],
    "IL": [
        "IL - Erick Matos Team",
        "IL - Gold List Realty Group",
        "IL - Team Alday",
        "IL - Team Arroyo",
        "IL - Team David",
        "IL - Team Reyes",
        "IL - The Agent Network",
        "IL - The Goodchild Team",
        "IL - Torres Prince Group",
        "IL LFRO",
        "IL Linda Locke TC",
        "IL The Dominguez Group",
        "Illinois",
    ],
    "IN": [
        "IN - Team David",
        "IN - The Dominguez Group",
        "IN Espinoza Realtors",
        "Indiana",
    ],
    "KS": [
        "KS - KC Signature Group",
        "Kansas",
    ],
    "MD": [
        "MD Kitty Njus",
        "Maryland",
    ],
    "MI": [
        "Michigan",
    ],
    "MO": [
        "MO - KC Signature Group",
        "Missouri",
    ],
    "MS": [
        "Mississippi",
    ],
    "NC": [
        "NC LFRO",
        "North Carolina",
    ],
    "NJ": [
        "NJ - The CMoore Group",
        "NJ - The J Prosper Team",
        "NJ - The Providel Group",
        "NJ Avila Property Group",
        "NJ Connected Alliance",
        "NJ Legacy Group",
        "NJ Sofia Rod TC",
        "NJ The Guild",
        "New Jersey",
    ],
    "NV": [
        "NV - Castillo Realty Group",
        "NV - Exclusive Team",
        "NV - Lopez Real Estate Group",
        "NV - Ricardo Sanchez Team",
        "NV - The Movement Team",
        "NV - Toro Realty",
        "NV - Umana Real Estate Group",
        "NV - VegasCarlos Group",
        "NV The Rich Group",
        "Nevada",
    ],
    "OK": [
        "OK Allison Crim TC",
        "OK LFRO",
        "Oklahoma",
    ],
    "OR": [
        "OR - Lopez Estate Group",
        "OR - Mendoza Property Group",
        "OR - Sanchez Team",
        "OR- Campos Property Group",
        "Oregon",
    ],
    "PR": [
        "Puerto Rico",
    ],
    "SC": [
        "SC LFRO",
        "South Carolina",
    ],
    "TN": [
        "TN - The Felts DeLozier Group",
        "Tennessee",
    ],
    "TX": [
        "TX - Angelique Burkett Team",
        "TX - BCertain Team",
        "TX - CB Realty Team",
        "TX - Cecy and Juan Group",
        "TX - Kyle Jefferson LTD",
        "TX - Social Realty",
        "TX - The Benavides Realty Team",
        "TX - The Closers Team",
        "TX - The Infinity Lux Group",
        "TX - The Tello Group",
        "TX Altura Real Estate Group",
        "TX Annette Mitchell TC",
        "TX Balladares Real Estate Team",
        "TX Brokers Edge Realty Group",
        "TX Burton Group",
        "TX Circa Real Estate",
        "TX Five One Two Realty Group",
        "TX HTX Finest Realty Group",
        "TX HTX Group",
        "TX Indy Quest Properties LLC",
        "TX LFRO",
        "TX Lampman Home Team",
        "TX Le Reve Realty Group",
        "TX MDT Flex",
        "TX MDT Flex - Circa",
        "TX MDT Flex - Collective",
        "TX MDT Flex - HTX FRG",
        "TX MDT Flex - LTD",
        "TX MDT Flex - Lampman",
        "TX MDT Flex - Nova",
        "TX MDT Flex - TTG",
        "TX MDT Flex - Tello",
        "TX Mark Dimas Team",
        "TX Michael Demian TC",
        "TX Nova Era Realty Group",
        "TX Ryan Smith Team",
        "TX Silvia Sandoval Realty",
        "TX Smedley TC Admin",
        "TX The Chad Smith Team",
        "TX The Collective",
        "TX The Jonathan Cook Team",
        "TX The Motion Group",
        "TX The Nino Team",
        "TX Tricia Turner Group",
        "TX Yaya Valencia TC",
        "TX Your New Texas Home Group",
        "TX- Select Realty Group",
        "Texas",
    ],
    "UT": [
        "UT - Utah Casa Team",
        "Utah",
    ],
    "VA": [
        "VA - Dosy Group",
        "VA AWICHO Properties",
        "VA The Washingtonian Group",
        "Virginia",
    ],
    "WI": [
        "Wisconsin",
    ],
    "XXXX": [
        "GA - Test Team Office",
        "State Name",
        "Test Office",
        "Test Office TC",
    ],
}